### ISSUE TITLE
[FEAT]: Organization, expressivity and clarity

### ISSUE THREAD

**Issue by brunolnetto** [thieunguyen5991/metaheuristics#9]
### Description

I just stumbled on your repository. We met in the past, and I showed you [this optimization method](https://github.com/asmove/baryopt). Today, I want you to give some tips on organization: 

1. GitHub provides a Wiki page, where you can list repository features;
2. Oftentimes, Metaheuristic optimization has sub-categories: discrete, continuous, operational, integer, schedule, and NP. Do some research, it will make your repository very expressive and helpful to others.

**Comment by thieu1995** [comment]
@brunolnetto ,

Thanks for suggesting. 
I think the 1st suggestion is good. However, for the 2nd suggestion, discrete, continuous, operational, integer, schedule, and NP they are from application's point of view, not from algorithm's point of view.

**Comment by brunolnetto** [comment]
There may be some categorization. You may even provide some meta-method `metaheur` with arguments keys `(input_args, method_name, method_config)`.
